Класс `tf.keras.layers.Dropout`, создающий dropout-слой.

In [3]:
import tensorflow as tf

In [ ]:
tf.keras.layers.Dropout(rate,                   # Шанс отбрасывания значения
                        noise_shape=None,       # Маска исключения
                        seed=None,
                        **kwargs)

Слой dropout случайным образом устанавливает для входных единиц значение 0 с частотой на каждом шаге во время обучения, что помогает предотвратить переобучение. Входы, для которых не установлено значение 0, умножаются на $\frac{1}{1 - rate}$.

Обратите внимание, что слой Dropout применяется только тогда, когда для обучения установлено значение `True`, так что во время вывода значения не удаляются. При использовании `model.fit` для обучения будет автоматически установлено значение `True`, а в других контекстах вы можете явно установить значение `training = True` при вызове слоя.

Это контрастирует с установкой `trainable = False` для слоя Dropout. `trainable` не влияет на поведение слоя, так как Dropout не имеет никаких переменных / весов, которые можно заморозить во время обучения

# Параметры

## `rate`

Тип: `float` в пределах отрезка [0, 1].

Описание: шанс отбрасывания значения. Каждое из значений входной матрицы либо обнуляется, либо умножается на $\frac{1}{1 - rate}$.

Примеры:<br>
• `Dropout(rate=0.2)` – возвращает слой dropout c параметром 0.2. 20% обнуления элемента входного тензора;<br>
• `Dropout(1.)` – возвращает слой dropout c параметром 1. Все входные данные заменяются нулями;<br>
• `Dropout(.0)` – возвращает слой dropout c параметром 0. Слой не влияет на входной тензор.<br>

##  `noise_shape`

Тип: 1D целочисленный тензор.

Описание: тензор, представляющий форму двоичной маски исключения, которая будет умножена на вход. Например, если ваши входные данные имеют форму `(batch_size, timesteps, features)`, и вы хотите, чтобы маска исключения была одинаковой для всех временных шагов, можете использовать `noise_shape = (batch_size, 1, features)`.

## `seed`

Тип: `int`.

Описание: положительное число, отвечающее за начальное состояние слоя (под сомнением).

*Рекомендуем для воспроизводимости экспериментов использовать `tf.random.set_seed(1)` перед каждым вызовом, так как `seed` в `Dropout` не обеспечивает воспроизводимых состояний.*

# Аргументы вызова слоя

## `inputs`

Тип: `np.ndarray`, `tf.Tensor` и аналогичные тензоры любого размера и формы.

Описание: входной тензор.

Примеры:<br>

• `Dropout(0.2)([1.,1.,1.])` – создаем слой dropout и сразу вызываем его с тензором `[1.,1.,1.]`;<br>
• `Dropout(rate=0.2)(np.array([1.,1.,1.]))` – аналогично предыдущему;<br>
• `Dropout(0.2)(np.ones((10, 2, 3))` – создаем слой dropout и вызываем его, подавая тензор формы (10, 2, 3) из единиц;


## `training`


Тип: `bool` (по умолчанию: `False`).

Описание: указывает, должен ли слой вести себя в режиме обучения (слой dropout выполняет свою функцию) или в режиме вывода (слой dropout ничего не делает). Режим обучения обычно активируется для всей модели.

#### Примеры

Если dropout без режима обучения, то тензор проходит через слой без изменений

In [1]:
import numpy as np
from tensorflow.keras.layers import Dropout

# Входной тензор
X = np.ones((5, 2))

# Создание и вызов слоя в тестовом режиме
Dropout(0.2)(X)

E0000 00:00:1740948510.277169  148931 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1740948510.287683  148931 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
I0000 00:00:1740948513.306608  148931 gpu_device.cc:2022] Created device /job:localhost/replica:0/task:0/device:GPU:0 with 5563 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4060 Laptop GPU, pci bus id: 0000:01:00.0, compute capability: 8.9


<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]], dtype=float32)>

В режиме обучения dropout активируется

In [4]:
# Задание состояния
tf.random.set_seed(3)

# Создание и вызов слоя в тренировочном режиме
Dropout(0.2)(X, training=True)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[1.25, 1.25],
       [1.25, 0.  ],
       [1.25, 1.25],
       [1.25, 1.25],
       [1.25, 1.25]], dtype=float32)>

## Пример

In [5]:
import numpy as np
from keras.layers import Dropout

In [6]:
# Инициализация входной матрицы
X = np.ones((5, 2))
X

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
# Создание слоя Dropout с параметром 0.2
dropout_layer = Dropout(rate=0.5)

Вызываем слой с аргументом созданной ранее матрицы.
Не забываем настроить слой на обучение, иначе тензор не изменится.

In [8]:
dropout_layer(X, training=True)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0., 2.],
       [2., 2.],
       [0., 2.],
       [0., 0.],
       [0., 0.]], dtype=float32)>